### ISSUE TITLE
Wrong variable name

### ISSUE THREAD

**Issue by LukyVj** [heyman/jquery-draggable-touch#3]
Hi, 

there is a small typo in the README. 
`console.log("drag ended on:", this, "at position:", post);` the `post` variable doesn't exist, it's `pos`

:) Have a nice day.

**Comment by heyman** [comment]
Thanks!

**Comment by LukyVj** [comment]
You're welcome :smile: 
By the way, really cool plugin dude. 

The only thing that I wanted to see, is a parameter to define on wich axis the drag should work. 

But I just removed some lines of your code for it :)
